### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by haigaru** [vconnex/vconnex-home-assistant#1]
Logger: homeassistant.config_entries
Source: custom_components/vconnex_cc/__init__.py:25 
Integration: Vconnex CC ([documentation](https://github.com/vconnex/vconnex-home-assistant)) 
First occurred: 8:23:31 PM (1 occurrences) 
Last logged: 8:23:31 PM

Error setting up entry [Vconnex CC] Home for vconnex_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/vconnex_cc/__init__.py", line 25, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by hiep292** [comment]
Fixed in v1.1.1
Thank you for your contribution!
